import assert from "node:assert/strict"
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import test from "node:test"
import config from "../kudzu.config.mjs"

test("generates canonical SEO output for Cloudflare static assets", async () => {
  const outDir = await mkdtemp(join(tmpdir(), "kudzu-seo-"))
  const routes = ["/", "/docs", "/example", "/releases/0.8.2", "/releases/0.8.15", "/releases/0.8.16", "/releases/0.8.17", "/releases/0.8.18", "/releases/0.8.19", "/releases/0.8.20", "/releases/0.8.21", "/releases/0.8.22", "/releases/0.8.23", "/releases/0.8.24", "/releases/0.8.25", "/releases/0.8.26", "/releases/0.8.27", "/releases/0.8.28", "/releases/0.8.29", "/releases/0.8.30", "/releases/0.8.31", "/releases/0.8.32", "/releases/0.8.33", "/releases/0.8.34", "/releases/0.8.35", "/releases/0.8.36", "/releases/0.8.37", "/releases/0.8.38", "/releases/0.8.39", "/releases/0.8.40", "/releases/0.8.41", "/releases/0.8.42", "/releases/0.8.43", "/releases/0.8.44", "/releases/0.8.45", "/releases/0.8.46", "/releases/0.8.47", "/releases/0.8.48", "/releases/0.8.49", "/releases/0.8.50", "/releases/0.8.51", "/releases/0.8.52", "/releases/0.8.53", "/releases/0.8.54", "/releases/0.8.55", "/releases/0.8.56", "/releases/0.8.57", "/example/blog/personal", "/example/blog/personal/demo", "/example/blog/personal/demo/a-room-made-for-reading"]
  routes.push("/releases/0.8.58")
  routes.push("/releases/0.8.59")
  routes.push("/releases/0.11.3")
  routes.push("/releases/0.11.4")
  routes.push("/releases/0.12.0")
  routes.push("/releases/0.12.1")
  routes.push("/releases/0.12.2")
  routes.push("/releases/0.12.3")
  routes.push("/releases/0.12.4")
  routes.push("/releases/0.13.0")
  routes.push("/releases/0.13.1")
  routes.push("/releases/0.13.2")
  routes.push("/releases/0.13.3")
  routes.push("/releases/0.14.0")
  routes.push("/releases/0.14.1")
  routes.push("/releases/0.14.2")
  routes.push("/releases/0.14.3")
  routes.push("/releases/0.15.1")
  routes.push("/releases/0.16.1")
  routes.push("/releases/0.16.3")
  try {
    for (const route of routes) {
      const directory = route === "/" ? outDir : join(outDir, route.slice(1))
      await mkdir(directory, { recursive: true })
      await writeFile(join(directory, "index.html"), "<!doctype html><html><head><title>Old</title><meta name=\"description\" content=\"Old\"></head><body></body></html>")
    }
    await config.afterBuild({ outDir, routes })

    const sitemap = await readFile(join(outDir, "sitemap.xml"), "utf8")
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/example\/blog\/personal\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.2\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.15\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.16\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.17\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.18\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.19\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.20\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.21\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.22\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.23\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.24\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.25\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.26\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.27\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.28\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.29\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.30\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.31\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.32\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.33\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.34\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.35\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.36\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.37\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.41\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.45\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.46\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.47\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.48\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.49\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.50\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.51\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.52\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.53\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.56\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.57\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.58\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.8\.59\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.11\.3\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.11\.4\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.12\.0\/<\/loc>/)
    assert.match(sitemap, /https:\/\/kudzujs\.cloud\/releases\/0\.14\.0\/<\/loc>/)
    assert.doesNotMatch(sitemap, /\/demo/)

    const showcase = await readFile(join(outDir, "example/blog/personal/index.html"), "utf8")
    assert.match(showcase, /<title>Personal Blog Example and Source \| Kudzu<\/title>/)
    assert.match(showcase, /rel="canonical" href="https:\/\/kudzujs\.cloud\/example\/blog\/personal\/"/)
    assert.doesNotMatch(showcase, /noindex/)

    const demo = await readFile(join(outDir, "example/blog/personal/demo/index.html"), "utf8")
    assert.match(demo, /name="robots" content="noindex,follow"/)
    assert.match(demo, /rel="canonical" href="https:\/\/kudzujs\.cloud\/example\/blog\/personal\/"/)
    assert.match(demo, /application\/ld\+json/)
  } finally {
    await rm(outDir, { recursive: true, force: true })
  }
})
